name: Lint workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'

jobs:
  lint:
    name: Lint workflows
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          mise_toml: |
            [tools]
            pinact = "latest"
            actionlint = "latest"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pinact
        run: |
          pinact run --check

      - name: Run actionlint
        run: |
          actionlint
